name: kasir_pintar
description: Aplikasi Kasir Pintar Mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  
  # Package Tambahan Utama:
  sqflite: ^2.3.0       # Untuk Database Lokal SQLite
  path: ^1.8.3          # Untuk Manajemen Path Folder Database
  intl: ^0.19.0         # Untuk Format Rupiah (Rp) & Tanggal Laporan

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
